# Generated by Django 5.0.2 on 2026-05-02 05:01

from django.db import migrations, models
import json


def convert_to_json(apps, schema_editor):
    """Convierte datos de texto a JSON"""
    Alumnos = apps.get_model('gestion_escolar_api', 'Alumnos')
    Maestros = apps.get_model('gestion_escolar_api', 'Maestros')
    
    # Convertir materias_json en Alumnos
    for alumno in Alumnos.objects.all():
        if alumno.materias_json:
            try:
                # Intentar parsear como JSON
                json.loads(alumno.materias_json)
            except (json.JSONDecodeError, TypeError):
                # Si no es JSON válido, convertir a lista vacía
                alumno.materias_json = []
                alumno.save()
    
    # Convertir materias_array en Maestros
    for maestro in Maestros.objects.all():
        if maestro.materias_array:
            try:
                # Intentar parsear como JSON
                json.loads(maestro.materias_array)
            except (json.JSONDecodeError, TypeError):
                # Si no es JSON válido, convertir a lista vacía
                maestro.materias_array = []
                maestro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0003_alumnos'),
    ]

    operations = [
        migrations.RunPython(convert_to_json),
        migrations.AlterField(
            model_name='alumnos',
            name='materias_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
