# Generated by Django 5.0.2 on 2026-05-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0004_alter_alumnos_materias_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias_array',
            new_name='materias_json',
        ),
    ]
