# Generated by Django 5.0.2 on 2026-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0006_administradores_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
