# Generated by Django 5.0.2 on 2026-05-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0007_alter_administradores_rfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
